import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const judge = {
    rock: { rock: 'draw', paper: 'loss', scissors: 'win' },
    paper: { rock: 'win', paper: 'draw', scissors: 'loss' },
    scissors: { rock: 'loss', paper: 'win', scissors: 'draw' }
  }

  const [myHand, setMyHand] = useState('');
  const [comHand, setComHand] = useState('');
  const [result, setResult] = useState('Victory or Defeat');
  const [status, setStatus] = useState(1);
  const [handleAble, setHandleAble] = useState(false);
  const [winNum, setWinNum] = useState(0);
  const [drawNum, setDrawNum] = useState(0);
  const [lossNum, setLossNum] = useState(0);

  useEffect(() => {
    const num = Math.floor(Math.random() * 3);
    num === 0 && setComHand('rock');
    num === 1 && setComHand('paper');
    num === 2 && setComHand('scissors');
  }, [status]);

  const getHand = (hand) => {
    setHandleAble(true);
    setMyHand(hand);
    setResult(judge[hand][comHand]);
  }

  useEffect(() => {
    result === 'win' && setWinNum((inData) => inData + 1);
    result === 'draw' && setDrawNum((inData) => inData + 1);
    result === 'loss' && setLossNum((inData) => inData + 1);
  }, [result]);

  const nextFnc = () => {
    setHandleAble(false);
    setStatus((status) => status + 1)
    setMyHand('');
    setComHand('');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my">
        <h3>{status}回目の勝負</h3>
        <button onClick={() => getHand('rock')} disabled={handleAble}>ROCK</button>
        <button onClick={() => getHand('paper')} disabled={handleAble}>PAPER</button>
        <button onClick={() => getHand('scissors')} disabled={handleAble}>SCISSORS</button>
        {myHand && <p>自分:{myHand}</p>}
        {!myHand && <p>自分:Push Button</p>}
        {myHand && <p>相手:{comHand}</p>}
        {!myHand && <p>相手:Thinking</p>}

        {myHand && <p>{result}</p>}
        {myHand && <button onClick={nextFnc}>Next</button>}
        <h3>{`${winNum}勝　${lossNum}敗　${drawNum}引分け`}</h3>
      </div>
    </div>
  )
}
